// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./reset.css";
import { AppProvider } from "@/context/AppContext";
import Navbar from "@/components/Funtional/Navbar/Navbar";
import Footer from "@/components/Funtional/Footer/Footer";
import { ReactQueryProvider } from "@/context/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col antialiased bg-blue-50`}
      >
        <ReactQueryProvider>
          <AppProvider>
            <div className="min-h-screen flex flex-col bg-blue-50">
              <Navbar />
              <main className="flex-grow pt-16 pb-28 bg-blue-50">
                {children}
              </main>
              <Footer />
            </div>
          </AppProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
